### ISSUE TITLE
glpi-agent.dll was not copied successfully

### ISSUE THREAD

**Issue by LordBat** [TECLIB/glpi-wince-agent#1]
Hi, i am testing the glpi-agent for winCE 5.0 and i have this error when is installing.

![image](https://user-images.githubusercontent.com/19165739/36257093-5102e8f2-1234-11e8-9a62-4107d01e29bc.png)

I need something more besides the cab to make it work?

Thanks and Regards!

**Comment by g-bougard** [comment]
Hi @LordBat 

WinCE Agent CAB installation was really tested on few devices & OS level. Maybe your system is very different than the ones we tested. Can you tell us more about the device and the OS version ?

Have you also checked device free space ?

**Comment by LordBat** [comment]
Hi @g-bougard  thx for the response, now we are testing on MOBILE COMPUTER WORKABOUT PRO 3 -WORKABOUT PRO4 and OmniXT15 with WinCE 5.0 and 6.0 but i am testing on 5.0 following the info of the cab published.

U need something more about it?

 - Have you also checked device free space ? Yes.

Thansks and regards!

**Comment by g-bougard** [comment]
Have you administrator rights on the devices to install the product ? The DLL not copied is probably the one installed in Windows\ folder as the agent needs to be registered as a service.
Without this DLL, you should still be able to run the agent manually for testing purpose.

About the devices, I know nothing about them and if you finally need better support you should contact our customer service to see what we can do.

I know CAB support is not perfect as I tried to do something generic but that was really difficult as WinCE versions don't handle CAB in a reliably way.

**Comment by LordBat** [comment]
Hi, i have administrator rights and i found the DLL but have 0 bytes.

![image](https://user-images.githubusercontent.com/19165739/36420417-c04748e2-1613-11e8-93d7-2282ec20ebac.png)

the program is installed and i put the info but seems cant connect (i suppose by the DLL)

![image](https://user-images.githubusercontent.com/19165739/36420480-02305910-1614-11e8-8190-a36076a715cf.png)

As you says the agent is not enable as service, this is an automatic configuration or can be enabled manually?

![image](https://user-images.githubusercontent.com/19165739/36420557-39e6347e-1614-11e8-85be-f70721086f4b.png)

Thanks for your response and time.   Regards!

**Comment by g-bougard** [comment]
Hi @LordBat 
as I'm working on an update for a client and for the same kind of issue, I discovered there maybe has an issue with the flash memory partitioning scheme.
The related device for me is a Motorola WT4090 running under WinCE 5.0. On such devices, it appears there are at least 2 FFS (Flash File System) used during cold boot to setup the devices with other DLL and specific registry keys.
On this device, the 2 FFS are: `\Platform` & `\Application`

Do you have this partition on your devices ? If yes, you would be able to benefit from the fix I'll prepare for that case. If not, you may be in another case but probably similar. I found this information in an "integrator guide" documentation for this device and in that last case you should look at this for your device to know how the setup should be done for your device.

**Comment by LordBat** [comment]
> Hi @LordBat
> as I'm working on an update for a client and for the same kind of issue, I discovered there maybe has an issue with the flash memory partitioning scheme.
> The related device for me is a Motorola WT4090 running under WinCE 5.0. On such devices, it appears there are at least 2 FFS (Flash File System) used during cold boot to setup the devices with other DLL and specific registry keys.
> On this device, the 2 FFS are: `\Platform` & `\Application`
> 
> Do you have this partition on your devices ? If yes, you would be able to benefit from the fix I'll prepare for that case. If not, you may be in another case but probably similar. I found this information in an "integrator guide" documentation for this device and in that last case you should look at this for your device to know how the setup should be done for your device.

Hi @g-bougard 

At this moment we are using Zebra Omnii XT15 as main device, this device have WinCE 6.0 and  the Operating System Files and Application Files are in the same FFS 

![1122](https://user-images.githubusercontent.com/19165739/49016861-21c02980-f166-11e8-8aa1-01bc2769a863.jpg)

**Comment by g-bougard** [comment]
Well, this seems not to be the same issue. That's a shame.
Can you confirm you still have the same issue with [v1.3](https://github.com/TECLIB/glpi-wince-agent/releases/tag/v1.3) I just released ? In your case, you can try the `glpi-agent-test-v1.3.cab` to have more debug in the `GLPI-Agent-installtion.txt` file.

**Comment by LordBat** [comment]
> Well, this seems not to be the same issue. That's a shame.
> Can you confirm you still have the same issue with [v1.3](https://github.com/TECLIB/glpi-wince-agent/releases/tag/v1.3) I just released ? In your case, you can try the `glpi-agent-test-v1.3.cab` to have more debug in the `GLPI-Agent-installtion.txt` file.

Sure! i will test

**Comment by g-bougard** [comment]
Hi @LordBat 
I just released the [GLPI-Agent for WinCE v1.4](https://github.com/TECLIB/glpi-wince-agent/releases/tag/v1.4).
Now `glpi-agent.dll` is installed in the installation folder and this should fix your issue (at least partly).
I would like to know if this effectively fixes your issue, but after I also would like to know if the agent remains installed and working after a cold boot.

**Comment by g-bougard** [comment]
Hi @LordBat 
I just release the [GLPI-Agent for WinCE v1.5](https://github.com/TECLIB/glpi-wince-agent/releases/tag/v1.5).
I used now `cabwiz.exe` from MS to generate the cab and I think this should fix your problem as this fixed the same kind of issue on few devices I finally got.

**Comment by g-bougard** [comment]
Hi @LordBat 
I released the [GLPI-Agent for WinCE v1.6](https://github.com/TECLIB/glpi-wince-agent/releases/tag/v1.6).
I tested this version heavily on few devices for which I had the same issue. It installs nicely and is stable.
I'm closing then this issue but feel free to reopen if you test the 1.6 and it doesn't fix the problem in your case.

**Comment by LordBat** [comment]
> Hi @LordBat
> I released the [GLPI-Agent for WinCE v1.6](https://github.com/TECLIB/glpi-wince-agent/releases/tag/v1.6).
> I tested this version heavily on few devices for which I had the same issue. It installs nicely and is stable.
> I'm closing then this issue but feel free to reopen if you test the 1.6 and it doesn't fix the problem in your case.

Hi! @g-bougard  sorry for the late response but i can confirm the 1.6v works GREAT! on  Psion Omnii RT15  7545 with WinCe 6. 


EDIT: How can see the scheduled time to run the agent? or how often is it configured?

If i have any issue i will notice you.  Thank you and great work!
